"""empty message

Revision ID: 4057e3231def
Revises: fcece89ceef9
Create Date: 2022-12-07 04:54:48.766348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4057e3231def'
down_revision = 'fcece89ceef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('order_details',
               existing_type=sa.VARCHAR(length=240),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('order_details',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=240),
               existing_nullable=True)

    # ### end Alembic commands ###
