"""empty message

Revision ID: ea3fd7409154
Revises: 4057e3231def
Create Date: 2022-12-07 05:11:05.684460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3fd7409154'
down_revision = '4057e3231def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_payment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('order_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.drop_column('order_status')
        batch_op.drop_column('total_payment')

    # ### end Alembic commands ###
